-- ============================================================
-- CareLink HMS — Migration 010: Lab Sample Tracking Columns
-- Adds all columns required by labSampleService.js that are
-- missing from the base lab_tests table (database-setup.sql).
-- Safe to re-run (IF NOT EXISTS / DO blocks with guards).
-- ============================================================

-- ── 1. Accession number ─────────────────────────────────────
-- Generated by labSampleService.generateAccessionNumber()
-- Format: LAB-YYYYMMDD-XXXX
ALTER TABLE lab_tests
  ADD COLUMN IF NOT EXISTS accession_number TEXT;

CREATE UNIQUE INDEX IF NOT EXISTS idx_lab_tests_accession
  ON lab_tests(accession_number)
  WHERE accession_number IS NOT NULL;

-- ── 2. Priority ─────────────────────────────────────────────
ALTER TABLE lab_tests
  ADD COLUMN IF NOT EXISTS priority TEXT DEFAULT 'routine'
  CHECK (priority IN ('routine', 'urgent', 'stat', 'emergency'));

-- ── 3. Clinical notes (separate from the existing 'notes') ──
-- labSampleService.js uses clinical_notes; base table has notes.
-- Both are kept — notes is for internal use, clinical_notes
-- carries the doctor's clinical indication for the test.
ALTER TABLE lab_tests
  ADD COLUMN IF NOT EXISTS clinical_notes TEXT;

-- ── 4. Specimen / collection columns ────────────────────────
ALTER TABLE lab_tests
  ADD COLUMN IF NOT EXISTS specimen_type TEXT;

ALTER TABLE lab_tests
  ADD COLUMN IF NOT EXISTS collected_by UUID REFERENCES users(id) ON DELETE SET NULL;

ALTER TABLE lab_tests
  ADD COLUMN IF NOT EXISTS collected_at TIMESTAMPTZ;

ALTER TABLE lab_tests
  ADD COLUMN IF NOT EXISTS collection_notes TEXT;

-- ── 5. Processing columns ────────────────────────────────────
ALTER TABLE lab_tests
  ADD COLUMN IF NOT EXISTS processed_by UUID REFERENCES users(id) ON DELETE SET NULL;

ALTER TABLE lab_tests
  ADD COLUMN IF NOT EXISTS processing_started_at TIMESTAMPTZ;

-- ── 6. Result tracking columns ──────────────────────────────
ALTER TABLE lab_tests
  ADD COLUMN IF NOT EXISTS result_details JSONB DEFAULT '{}';

ALTER TABLE lab_tests
  ADD COLUMN IF NOT EXISTS is_abnormal BOOLEAN DEFAULT FALSE;

ALTER TABLE lab_tests
  ADD COLUMN IF NOT EXISTS completed_by UUID REFERENCES users(id) ON DELETE SET NULL;

-- ── 7. Expand status CHECK constraint ───────────────────────
-- Base table only allows: pending, in_progress, completed, cancelled
-- labSampleService.js also uses: ordered, collected, processing
-- Strategy: drop the inline CHECK, recreate with full value set.
DO $$
BEGIN
  -- Drop the old constraint if it exists (auto-named by Postgres)
  IF EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE table_name = 'lab_tests'
      AND constraint_type = 'CHECK'
      AND constraint_name = 'lab_tests_status_check'
  ) THEN
    ALTER TABLE lab_tests DROP CONSTRAINT lab_tests_status_check;
  END IF;

  -- Add the expanded constraint
  -- (IF NOT EXISTS is not available for ADD CONSTRAINT before PG15,
  --  so we guard with the check above)
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE table_name = 'lab_tests'
      AND constraint_type = 'CHECK'
      AND constraint_name = 'lab_tests_status_check'
  ) THEN
    ALTER TABLE lab_tests
      ADD CONSTRAINT lab_tests_status_check
      CHECK (status IN (
        'pending',
        'ordered',
        'in_progress',
        'collected',
        'processing',
        'completed',
        'cancelled'
      ));
  END IF;
END;
$$;

-- ── 8. Helpful indexes ───────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_lab_tests_priority
  ON lab_tests(priority);

CREATE INDEX IF NOT EXISTS idx_lab_tests_collected_at
  ON lab_tests(collected_at DESC)
  WHERE collected_at IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_lab_tests_completed_at
  ON lab_tests(completed_at DESC)
  WHERE completed_at IS NOT NULL;

-- ============================================================
-- Migration 010 complete
-- Altered: lab_tests
--   Added:  accession_number, priority, clinical_notes,
--           specimen_type, collected_by, collected_at,
--           collection_notes, processed_by, processing_started_at,
--           result_details, is_abnormal, completed_by
--   Fixed:  status CHECK now includes ordered, collected, processing
-- ============================================================
